environment:
  nodejs_version: "6"

environment:
  FIREBASE_TOKEN:
    secure: epNSsEceKy4M873j7s2rHIgXmOu3jaCwqkQkH+NbPNRGcmHBkFOA8Rp+d+4UyPcK

branches:
  only:
  - master

build: off

install:
  - ps: Install-Product node $env:nodejs_version

before_test:
  - npm install -g firebase-tools
  - cd functions && npm install && cd ..


test_script:
  - firebase deploy --token %FIREBASE_TOKEN%
