environment:
  nodejs_version: "6"

only_commits:
  message: /[bveyor]/


branches:
  only:
  - master

build: off

install:
  - ps: Install-Product node $env:nodejs_version

before_test:
  - npm install -g firebase-tools
  - cd functions && npm install && cd ..


test_script:
  - firebase deploy --token %DEPLOY_TOKEN%
